version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: app
    volumes:
      - ./:/var/www/html
    networks:
      - network
    depends_on:
      - nginx
    command: ["php-fpm"]
    build:
      context: .
      dockerfile: docker/php/Dockerfile

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/var/www/html
    ports:
      - "80:80"
    networks:
      - network

networks:
  network:
    driver: bridge
